### ISSUE TITLE
Laman Panduan Kontribusi tidak ditemukan

### ISSUE THREAD

**Issue by bringsik100** [belajarpythoncom/belajarpython.com#25]
Alamat link di judul memakai https://belajarpython.com/contributing/how-to-contribute.html
Tapi alamat di paragraf memakai alamat https://belajarpython.org/contributing/how-to-contribute.html

Beda .com dan .org

**Comment by bringsik100** [comment]
Laman  [good first issues](https://github.com/belajarpythoncom/belajarpythoncom.com/issues) tidak ditemukan

**Comment by bringsik100** [comment]
Maaf, tadi belum baca peraturan di CONTRIBUTING.md

**Comment by purwnt** [comment]
Terimakasih untuk kontribusi isu-nya 👍 @bringsik100
