### ISSUE TITLE
[Typo] Di dalam "Variabel Python"

### ISSUE THREAD

**Issue by ditokp** [belajarpythoncom/belajarpython.com#9]
Screenshot:
![2018-12-31-155434_1366x768_scrot](https://user-images.githubusercontent.com/27815899/50557132-a0375a80-0d14-11e9-8d56-4bcc9d59e6df.png)

"natinya" -> "nantinya"

**Comment by Anon6372098** [comment]
hmm, harus sampai open issue kah ? :V

**Comment by purwnt** [comment]
> Screenshot:
> ![2018-12-31-155434_1366x768_scrot](https://user-images.githubusercontent.com/27815899/50557132-a0375a80-0d14-11e9-8d56-4bcc9d59e6df.png)
> 
> "natinya" -> "nantinya"

Okay, tidak terimakasih atas issue-nya

**Comment by purwnt** [comment]
Fixed
