### ISSUE TITLE
Highlight.js Not Working

### ISSUE THREAD

**Issue by dendyaziz** [belajarpythoncom/belajarpython.com#97]
Remote URL sudah dipindah secara permanen

Dari:
https://highlightjs.org/static/highlight.min.js

Ke:
https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js

Mohon yang sempat untuk create PR

![Screenshot 2023-12-02 at 20 24 25](https://github.com/belajarpythoncom/belajarpython.com/assets/35209381/0b0f719e-e8e9-4a99-8bf9-0ace974c4755)

Saat ini:
![Screenshot 2023-12-02 at 20 24 10](https://github.com/belajarpythoncom/belajarpython.com/assets/35209381/868ad426-c9da-4bda-918e-16228f85d484)

Sebelumnya
![Screenshot 2023-12-02 at 20 29 16](https://github.com/belajarpythoncom/belajarpython.com/assets/35209381/b0b3f7d6-e466-4ec9-a1b7-e5b0133dc8e6)

**Comment by purwnt** [comment]
Sudah diperbaiki. Terimakasih atas kontribusinya @dendyaziz
